/**:
  ros__parameters:
    agents:
      ids: ["cf_0", "cf_1"]
      initial_positions_x: [0.0, 1.0]
      initial_positions_y: [0.0, 1.0]
    tasks:
      # Task area in meters: rectangle [min, max)
      min_x: 0.5
      max_x: 2.5
      min_y: 0.5
      max_y: 2.5
      # Obstacle positions in meters
      obstacles_positions_x: [2.5]
      obstacles_positions_y: [2.5]